event-exporter/sinks/stackdriver/sink_test.go

Make them less flaky by replacing sleeps by timeouts/channels.

Make event-exporter unit tests more robust

---

event-exporter/OWNERS
kubelet-to-gcm/OWNERS
prometheus-to-sd/OWNERS

They're not needed in this repo

Remove OWNERS files

---

event-exporter/Makefile
event-exporter/sinks/stackdriver/sink.go
event-exporter/sinks/stackdriver/sink_test.go

Pushing https://github.com/kubernetes/contrib/pull/2641

Fix event exporter spam

---

fluentd-gcp-image/Makefile

Pushing https://github.com/kubernetes/contrib/pull/2640

Bump fluentd image version

---

CONTRIBUTING.md

Copied from https://github.com/GoogleCloudPlatform/python-runtime/blob/master/CONTRIBUTING.md
/cc @piosz

Update CONTRIBUTING.md to conform to the GCP template

---

prometheus-to-sd/main.go

Enable on port 6060 of prometheus-to-sd pprof.

Add pprofiler to the prometheus-to-sd.

---

prometheus-to-sd/main.go
prometheus-to-sd/translator/metric_descriptor_cache.go
prometheus-to-sd/translator/stackdriver.go
prometheus-to-sd/translator/translator.go

Add component names to logs, replace some warning log messages with
info and update verbosity level for some of them.

Improve logging of prometheus-to-sd.

---

fluentd-gcp-image/README.md

Fixes https://github.com/GoogleCloudPlatform/k8s-stackdriver/issues/44
/cc @piosz

[fluentd-gcp-image] Update README.md

---

custom-metrics-stackdriver-adapter/README.md
hack/verify-flags/exceptions.txt

Preview: https://github.com/kawych/k8s-stackdriver/blob/docs/custom-metrics-stackdriver-adapter/README.md

Add README to Custom Metrics - Stackdriver Adapter

---

event-exporter/example/event-exporter.yaml

Use beta apis, update the image, and create a new CRB.

Update config for example

---

kubelet-to-gcm/monitor/kubelet/translate.go

With current approach (using currentTime - 1 minute), we are going to
expose wrong values for metrics, because from Stackdriver side it looks
that instead of setting new value "X" for metric we are increasing it by
"X".

Use a correct start time for Cumulative metrics.

---

README.md

Fixes https://github.com/GoogleCloudPlatform/k8s-stackdriver/issues/103
@x13n Please take a look

Fix 404 in README.md

---

fluentd-gcp-scaler/Makefile
fluentd-gcp-scaler/scaler.sh

Make sure to update only fluentd-gcp container resources

---

prometheus-to-sd/config/dynamic_source.go
prometheus-to-sd/config/source_config.go
prometheus-to-sd/config/source_config_test.go
prometheus-to-sd/main.go

Add path to dynamic source configs
Handle empty path
Fix component name bug
Add tests for empty path

[prometheus-to-sd] Fix small bugs, add path in dynamic source

---

prometheus-to-sd/config/dynamic_source.go
prometheus-to-sd/config/dynamic_source_test.go

Add tests for source validation

[prometheus-to-sd] Improve source validation

---

prometheus-to-sd/Makefile
prometheus-to-sd/README.md

Bump prometheus-to-sd version tag for releasing

---

custom-metrics-stackdriver-adapter/Makefile
custom-metrics-stackdriver-adapter/examples/direct-to-sd/Makefile
event-adapter/Makefile
event-exporter/Makefile
fluentd-gcp-image/Makefile
fluentd-gcp-scaler/Makefile
kubelet-to-gcm/Makefile
prometheus-to-sd/Makefile

Also remove some obsolete instructions.
Please take a look @kawych @loburm @serathius @piosz @cezarygerard @Szetty @anjensan

Update gcr.io/google-containers to staging-k8s.gcr.io in all the projects

---

event-exporter/Dockerfile
fluentd-gcp-image/Dockerfile
fluentd-gcp-scaler/Dockerfile
prometheus-to-sd/Dockerfile

Updates images of k8s-stackdriver components to new debian image with fixed security vulnerabilities.

Update images to debian-base-amd:0.3.2

---

fluentd-gcp-scaler/Makefile
fluentd-gcp-scaler/scaler.sh

Remove excessive logging in fluentd-gcp-scaler

---

custom-metrics-stackdriver-adapter/README.md
custom-metrics-stackdriver-adapter/deploy/production/adapter_new_resource_model.yaml
custom-metrics-stackdriver-adapter/examples/direct-to-sd/README.md
custom-metrics-stackdriver-adapter/examples/direct-to-sd/custom-metrics-sd.yaml
custom-metrics-stackdriver-adapter/examples/prometheus-to-sd/README.md
hack/verify-flags/exceptions.txt

Ready for review.
DO NOT SUBMIT until new Stackdriver resource model is officially rolled out

Add documentation for Custom Metrics - Stackdriver Adapter based on new Stackdriver resource model

---

event-exporter/README.md
event-exporter/main.go
event-exporter/sinks/stackdriver/sink.go
event-exporter/sinks/stackdriver/writer.go
event-exporter/watchers/events/handler.go

doc change re: The resourceVersion for the provided watch is too old

---

prometheus-to-sd/README.md
prometheus-to-sd/kubernetes/prometheus-to-sd-kube-state-metrics.yaml

README.md: Fixed wording: deployment/pod.
kubernetes/prometheus-to-sd-kube-state-metrics.yaml: Updated to the last versions of the containers.

Fixed resource name, updated containers to last versions available

---

event-exporter/README.md
event-exporter/main.go
event-exporter/sinks/stackdriver/sink.go
event-exporter/sinks/stackdriver/writer.go
event-exporter/watchers/events/handler.go
hack/install-verify-tools.sh

Added comment about resource version too old warning

---

prometheus-to-sd/Makefile
prometheus-to-sd/config/dynamic_source.go

Prepare release of prometheus-to-sd with basic support of summary metrics and possibility to downcase metric names.
Release notes:
* added basic support of summary metrics
* added flag downcase-metric-names to automatically fix naming convention in prometheus metrics.

Bump version of prometheus-to-sd.

---

fluentd-gcp-image/Dockerfile
fluentd-gcp-image/Makefile
fluentd-gcp-scaler/Dockerfile
fluentd-gcp-scaler/Makefile

New image has security fixes for 02.2019

Update debian base image to 0.4.1

---

prometheus-to-sd/Makefile

New release embeds licensing file into image

Relase prometheus-to-sd v0.5.1

---

event-exporter/Dockerfile

Thanks @x13n for the original distroless change!

An improvement of the distroless image path.

---

prometheus-to-sd/Dockerfile

Thanks @loburm for rebasing to distroless!

Fix a Dockerfile linter

---

hack/verify-flags/known-flags.txt
prometheus-to-sd/main.go

Added delayed shutdown timeout

Added delayed shutdown timeout

---

event-exporter/Makefile
event-exporter/main.go

Use protobufs for apiserver communication in event-exporter

---

prometheus-to-sd/translator/prometheus.go
prometheus-to-sd/translator/prometheus_test.go

Reuse the same transport to avoid recreating it all the time.

Fix goroutine leak.

---

.travis.yml
custom-metrics-stackdriver-adapter/Dockerfile
event-adapter/pkg/apiserver/installer/apiserver_test.go
event-exporter/Dockerfile
hack/for-go-proj.sh
hack/verify-flags/exceptions.txt
prometheus-to-sd/Dockerfile
prometheus-to-sd/translator/prometheus_test.go
prometheus-to-sd/translator/translator.go

All components right now are using either 1.9 or 1.10. Switch all of them to 1.13 and change travis configuration to test only against that version.

Switch all components to 1.13.

---

prometheus-to-sd/kubernetes/prometheus-to-sd-kube-state-metrics.yaml

This should use the newest prom-to-sd version.

Update example prom-to-sd deployment

---

event-exporter/sinks/stackdriver/sink.go
event-exporter/sinks/stackdriver/sink_test.go
event-exporter/watchers/events/watcher.go

https://travis-ci.org/github/GoogleCloudPlatform/k8s-stackdriver/pull_requests
/cc @kawych

Gofmt code to fix CI

---

custom-metrics-stackdriver-adapter/README.md
custom-metrics-stackdriver-adapter/adapter.go
custom-metrics-stackdriver-adapter/pkg/adapter/provider/provider.go
custom-metrics-stackdriver-adapter/pkg/adapter/provider/translator.go
custom-metrics-stackdriver-adapter/pkg/adapter/provider/translator_test.go
hack/verify-flags/known-flags.txt

https://github.com/GoogleCloudPlatform/k8s-stackdriver/issues/336

Add enable-container-metrics feature to custom-metrics-stackdriver-adapter

---

custom-metrics-stackdriver-adapter/adapter.go
custom-metrics-stackdriver-adapter/pkg/adapter/coreprovider/client.go
custom-metrics-stackdriver-adapter/pkg/adapter/coreprovider/coreprovider_test.go
custom-metrics-stackdriver-adapter/pkg/adapter/coreprovider/provider.go
custom-metrics-stackdriver-adapter/pkg/adapter/translator/query_builder.go
custom-metrics-stackdriver-adapter/pkg/adapter/translator/query_builder_test.go
custom-metrics-stackdriver-adapter/pkg/adapter/translator/response_translator.go
custom-metrics-stackdriver-adapter/pkg/adapter/translator/response_translator_test.go
hack/verify-flags/exceptions.txt

Core metrics functionality + Unit tests

Core metrics functionality

---

custom-metrics-stackdriver-adapter/Makefile

Bump version to v0.12.0

---

custom-metrics-stackdriver-adapter/Makefile

Bump CMSA version to v0.12.1

---

custom-metrics-stackdriver-adapter/pkg/adapter/translator/response_translator.go
custom-metrics-stackdriver-adapter/pkg/adapter/translator/response_translator_core.go
hack/verify-flags/exceptions.txt

Refactor, added struct PodResult/NodeResult

Split response_translator file

---

custom-metrics-stackdriver-adapter/deploy/production/adapter.yaml
custom-metrics-stackdriver-adapter/deploy/production/adapter_new_resource_model.yaml
custom-metrics-stackdriver-adapter/deploy/staging/adapter_new_resource_model.yaml
custom-metrics-stackdriver-adapter/deploy/staging/adapter_old_resource_model.yaml
custom-metrics-stackdriver-adapter/deploy/test/adapter_new_resource_model_with_core_metrics.yaml

Update images to v0.12.0 release

---

custom-metrics-stackdriver-adapter/pkg/adapter/coreprovider/client.go
custom-metrics-stackdriver-adapter/pkg/adapter/coreprovider/client_test.go
custom-metrics-stackdriver-adapter/pkg/adapter/translator/query_builder_test.go
custom-metrics-stackdriver-adapter/pkg/adapter/translator/response_translator_core.go
custom-metrics-stackdriver-adapter/pkg/adapter/translator/response_translator_test.go
custom-metrics-stackdriver-adapter/pkg/adapter/translator/translator_test_utils.go
hack/verify-flags/exceptions.txt

Feature & Tests - starting with synchronous implementation

Add handling more than 100 pods/nodes to Core Metrics API

---

fluentd-gcp-scaler/Dockerfile

Use newer debian base image to fix vulnerabilities.

Update debian base image to fix vulnerabilities

---

custom-metrics-stackdriver-adapter/examples/direct-to-sd/Dockerfile
custom-metrics-stackdriver-adapter/examples/direct-to-sd/Makefile

Bump debian base

---

hack/verify-flags/known-flags.txt
kubelet-to-gcm/monitor/config/initialize.go
kubelet-to-gcm/monitor/kubelet/client.go
kubelet-to-gcm/monitor/kubelet/source.go
kubelet-to-gcm/monitor/main/daemon.go
kubelet-to-gcm/monitor/poll.go

Allow communicating with summary API via authenticated kubelet port using certificate.

Allow communicating with summary API via authenticated kubelet port

---

custom-metrics-stackdriver-adapter/Makefile

Bump custom metrics stackdriver adapter version to v0.12.2

---

custom-metrics-stackdriver-adapter/deploy/production/adapter.yaml
custom-metrics-stackdriver-adapter/deploy/production/adapter_new_resource_model.yaml
custom-metrics-stackdriver-adapter/deploy/staging/adapter_new_resource_model.yaml
custom-metrics-stackdriver-adapter/deploy/staging/adapter_old_resource_model.yaml
custom-metrics-stackdriver-adapter/deploy/test/adapter_new_resource_model_with_core_metrics.yaml

This PR will bump custom metrics stackdriver adapter image version to v0.12.2

Bump custom metrics stackdriver adapter image version to v0.12.2

---

event-exporter/example/event-exporter.yaml

- update the apiversion for Deployment and ClusterRoleBinding 
- deployment namespace set to `default`

update to latest apiVersion for Deployment and ClusterRoleBinding

---

custom-metrics-stackdriver-adapter/examples/prometheus-to-sd/README.md
custom-metrics-stackdriver-adapter/examples/prometheus-to-sd/custom-metrics-prometheus-sd.yaml

Related PR: https://github.com/GoogleCloudPlatform/k8s-stackdriver/pull/487

Update Prometheus Example

---

custom-metrics-stackdriver-adapter/deploy/production/adapter.yaml
custom-metrics-stackdriver-adapter/deploy/production/adapter_new_resource_model.yaml
custom-metrics-stackdriver-adapter/deploy/staging/adapter_new_resource_model.yaml
custom-metrics-stackdriver-adapter/deploy/staging/adapter_old_resource_model.yaml
custom-metrics-stackdriver-adapter/deploy/test/adapter_new_resource_model_with_core_metrics.yaml

Please take a look when you get a chance, thanks @laoj2

Bump custom-metrics-stackdriver-adapter version

---

.gitignore

fixing Security Policy violation Binary Artifacts #501

delete binary from kubelet-to-gcm build directoy

---

custom-metrics-stackdriver-adapter/deploy/production/adapter_new_resource_model.yaml

Update memory values of limits and requests

---

custom-metrics-stackdriver-adapter/README.md

fixes invisible args in custom-metrics-stackdriver-adapter README

fix: fixes invisible args in custom-metrics-stackdriver-adapter README

---

custom-metrics-stackdriver-adapter/Makefile

Update makefile patch version

---

custom-metrics-stackdriver-adapter/Makefile

Fix: https://github.com/GoogleCloudPlatform/k8s-stackdriver/issues/806

Prepare to release custom-metrics-stackdriver-adapter v0.15.2

---

custom-metrics-stackdriver-adapter/go.mod
custom-metrics-stackdriver-adapter/go.sum

Fix: https://github.com/GoogleCloudPlatform/k8s-stackdriver/issues/806

bump net to 0.33.0

---

custom-metrics-stackdriver-adapter/deploy/production/adapter.yaml
custom-metrics-stackdriver-adapter/deploy/production/adapter_new_resource_model.yaml
custom-metrics-stackdriver-adapter/deploy/staging/adapter_new_resource_model.yaml
custom-metrics-stackdriver-adapter/deploy/staging/adapter_old_resource_model.yaml
custom-metrics-stackdriver-adapter/deploy/test/adapter_new_resource_model_with_core_metrics.yaml

fix: https://github.com/GoogleCloudPlatform/k8s-stackdriver/issues/806

Update image version to v0.15.2-gke.1 to fix vuls

---

event-exporter/main.go

Add a `enable-pod-owner-label` flag (default to true) that can toggle the pod owner labels feature on and off
Change-Id: Ie4ddd25667ead0ff06ce7b37b6d00c2a94d1eba5

event-exporter: flag to turn on/off pod owner label
