GoogleCloudPlatform/k8s-stackdriver

hack/verify-flags/exceptions.txt
hack/verify-flags/known-flags.txt
prometheus-to-sd/config/pod_config.go
prometheus-to-sd/config/source_config_test.go
prometheus-to-sd/main.go
prometheus-to-sd/translator/stackdriver.go
prometheus-to-sd/translator/stackdriver_test.go
prometheus-to-sd/translator/translator.go
prometheus-to-sd/translator/translator_test.go

Add flag pod-id and namespace-id that are used to create correct
monitored resource object for the stackdriver.
Additionally some small refactoring to improve readability.
This PR is base on https://github.com/kubernetes/contrib/pull/2649,
which was already merged in the contrib repository.

Added few more flags with information about pod.

---

prometheus-to-sd/config/source_config.go
prometheus-to-sd/config/source_config_test.go
prometheus-to-sd/main.go
prometheus-to-sd/translator/metric_descriptor_cache.go
prometheus-to-sd/translator/metric_descriptor_cache_test.go
prometheus-to-sd/translator/stackdriver.go
prometheus-to-sd/translator/translator.go
prometheus-to-sd/translator/translator_test.go

This PR includes few minor changes that fixes issues in the prometheus-to-sd component:
1. Component is not trying to update metric descriptor if this metric was not whitelisted.
2. Updates metric descriptor if new label was added.
3. Don't send broken metrics to the stackdriver (for example when name is longer than 100 characters or number of labels bigger than 10)
4. If sending of batch of timeserieses to the Stackdriver fails, correct number of sent timeserieses is logged.

Update labels of metric descriptors if they change

---

hack/verify-flags/known-flags.txt
prometheus-to-sd/main.go
prometheus-to-sd/translator/translator.go
prometheus-to-sd/translator/translator_test.go

If flag is set to true then component name is removed from metrics that
have such prefix. For example etcd_version_info is going to be
represented as container.googleapis.com/etcd/version_info.

Introduce omit-component-name flag.

---

event-exporter/sinks/stackdriver/sink_test.go

Since sink sends requests asynchronously, there's a delay between calling OnAdd method and calling Write method in another goroutine. There should have been a timeout until the latter method is actually called, without this timeout it was possible for the main goroutine to reach the check before second goroutine gets the chance to add enough object to the channel.
Fixes https://github.com/GoogleCloudPlatform/k8s-stackdriver/issues/12

Fix race in event-exporter tests

---

prometheus-to-sd/translator/metric_descriptor_cache.go
prometheus-to-sd/translator/translator.go
prometheus-to-sd/translator/translator_test.go

If stored in the stackdriver MetricDescritor has type value DOUBLE or
BOOL, then convert value received from the prometheus to the correct
value before pushing it to the stackdriver.

Add support of double and boolean values.

---

prometheus-to-sd/Makefile

This version is able to handle double and bool values.
Pprof is added.

Update version of prom-to-sd to 0.2.1.

---

hack/verify-flags/exceptions.txt
prometheus-to-sd/README.md
prometheus-to-sd/kubernetes/prometheus-to-sd-kube-state-metrics.yaml

Simple README documentation and example .yaml file for deploying
prometheus-to-sd as a side container for kube-state-metrics.
fix https://github.com/kubernetes/contrib/issues/2582

Add simple documentation for prometheus-to-sd.

---

event-exporter/Makefile
event-exporter/sinks/stackdriver/sink.go
event-exporter/sinks/stackdriver/sink_test.go
event-exporter/watchers/events/handler.go
event-exporter/watchers/events/handler_test.go

Because it's a valid behavior for the situation with empty backing storage.

[event-exporter] Treat update with empty previous object as non-error

---

event-exporter/Makefile
event-exporter/sinks/stackdriver/sink_config.go
event-exporter/sinks/stackdriver/sink_factory.go

Makes it possible to specify a location in the event-exporter configuration, that will be used to associate the events with.
/cc @piosz

[event-exporter] Propagate location from the configuration parameters

---

event-exporter/Makefile
event-exporter/sinks/stackdriver/sink.go

In the clusters with CA, the number of metric streams will continuously grow if the host is included.
@piosz

[event-exporter] Remove host from the metric labels

---

custom-metrics-stackdriver-adapter/adapter-beta.yaml

After PR: https://github.com/kubernetes/kubernetes/pull/54854 HPA can read custom metrics with default permissions.

Don't set custom metrics reader permission in adapter deployment

---

custom-metrics-stackdriver-adapter/adapter-beta.yaml

Reverts GoogleCloudPlatform/k8s-stackdriver#65
It triggered this issue: https://github.com/kubernetes/kubernetes/issues/55805

Revert "Don't set custom metrics reader permission in adapter deployment"

---

custom-metrics-stackdriver-adapter/adapter-beta.yaml

Fixes: https://github.com/kubernetes/kubernetes/issues/55805
After this change I can get HPA with custom metrics working on GKE, 
without any RBAC-related issues.

Stop using incorrect requestheader CA

---

custom-metrics-stackdriver-adapter/examples/direct-to-sd/README.md
custom-metrics-stackdriver-adapter/examples/prometheus-to-sd/README.md

Existing command doesn't work:
$ kubectl create -f https://github.com/GoogleCloudPlatform/k8s-stackdriver/blob/master/custom-metrics-stackdriver-adapter/examples/direct-to-sd/custom-metrics-sd.yaml 
error: error converting YAML to JSON: yaml: line 314: mapping values are not allowed in this context
Using raw successfully starts exporter pod.

Fix example command

---

custom-metrics-stackdriver-adapter/examples/direct-to-sd/README.md

I think that logs is a kubectl command and not a resource that you load with the get command.

remove get from kubectl logs

---

prometheus-to-sd/Dockerfile

This should use the latest base to get the latest CVE fixes

Update prom-to-sd to latest base image

---

fluentd-gcp-image/Dockerfile

This should use the latest debian-base image to get the latest CVE fixes.

Update fluentd-gcp to use the 0.3 base image

---

event-exporter/Makefile
event-exporter/sinks/stackdriver/sink.go

This PR removes increasing `successfully_sent_entry_count` metric when sending "event exported started watching".
This way we achieve desirable behavior of having equal `received_entry_count` `successfully_sent_entry_count` metrics.

Avoid increasing successfully sent metric for event exporter internal logs

---

custom-metrics-stackdriver-adapter/pkg/adapter/server/start.go

#97 
This patch replace ComputeTokenSource by DefaultTokenSource in order to allow to use service accounts in custom-metrics-stackdriver-adapter.
It is the first step to use it outside of GCE/GKE.

Use DefaultTokenSource in custom-metrics-stackdriver-adapter

---

fluentd-gcp-image/Makefile
fluentd-gcp-image/run.sh

Remove hack to copy systemd libraries from host in fluentd-gcp container. That hack was present to make fluentd-gcp be able to access journal files from COS, which are created using LZ4 compression. But debian-base:0.3 (on which this is now based) already supports both +XZ and +LZ4 compression, so this hack is no longer needed.
That hack breaks on, say, CentOS 7, where the systemd libraries link to other versions of libraries that are not available in the fluentd-gcp.
For more context, see some discussion [here](https://github.com/kubernetes/kubernetes/pull/41407#issuecomment-363971712).
Also clean up the /run.sh shell script and effectively stop using it altogether (though still ship it, for compatibility.) See individual commits for the individual cleanup steps.
Bump version to 2.0.16 …

Remove hack to copy systemd libraries from host in fluentd-gcp container.

---

prometheus-to-sd/README.md

Otherwise we'd have to update README at every release.

Remove version tag from the GCR reference

---

prometheus-to-sd/main.go
prometheus-to-sd/translator/metric_descriptor_cache.go
prometheus-to-sd/translator/metric_descriptor_cache_test.go

Previously we have been missing check of correctness for metrics with
prefix "container.googleapis.com". As a result if metric has changed all
batch of timeserieses was failing. Now such metric is going to be
ignored and warning logged.

Validate metric descriptors before pushing.

---

fluentd-gcp-scaler/Makefile
fluentd-gcp-scaler/scaler.sh

Step towards fixing https://github.com/kubernetes/kubernetes/issues/61190, which is k8s 1.10.0 release blocker.

Bugfix: don't call kubectl set resources when there would be no effect.

---

event-exporter/Dockerfile
event-exporter/Makefile
fluentd-gcp-image/Dockerfile
fluentd-gcp-image/Makefile

Use the new version of base images. Additionally, update the names to the new ones
@cjcullen Please review

Update fluentd-gcp and event-exporter base image

---

custom-metrics-stackdriver-adapter/Makefile
custom-metrics-stackdriver-adapter/deploy/staging/adapter_new_resource_model.yaml
custom-metrics-stackdriver-adapter/deploy/staging/adapter_old_resource_model.yaml

This bumps the adapter image to v0.5.0 and uses newest version in staging deployments.

Bump Custom Metrics - Stackdriver Adapter to v0.5.0

---

kubelet-to-gcm/Makefile
prometheus-to-sd/Makefile

This releases includes correct instance name.

Bump version of prometheus-to-sd and kubelet-to-gcm.

---

custom-metrics-stackdriver-adapter/README.md
custom-metrics-stackdriver-adapter/deploy/production/adapter.yaml

This PR:
- Updates deploy/production/adapter.yaml deployment to v0.5.0
- Changes recommended deployment from adapter-beta.yaml to deploy/production/adapter.yaml
- Adds information that External Metrics API is now supported

Add information on External Metrics do documentation.

---

event-exporter/Makefile
event-exporter/sinks/stackdriver/monitored_resource_factory_config.go

event exporter fix cluster location trailing whitespace
plus patch version bump

event exporter fix cluster location trailing whitespace

---

kubelet-to-gcm/monitor/kubelet/translate.go
kubelet-to-gcm/monitor/kubelet/translate_test.go

Deduplicating for whole scrape caused dropping metrics when there are
multiple pods with containers that have same name.
closes https://github.com/GoogleCloudPlatform/k8s-stackdriver/issues/161

Move container stats deduplication logic under pod

---

kubelet-to-gcm/monitor/kubelet/translate.go
kubelet-to-gcm/monitor/kubelet/translate_test.go

CAdvisor skips that metric on fresh containers, when he didn't have time
to calculate it.
closes https://github.com/GoogleCloudPlatform/k8s-stackdriver/issues/160

Allow missing usageNanoCores

---

kubelet-to-gcm/Makefile

CHANGELOG
```
* Fix dropping metrics for containers with same name (https://github.com/GoogleCloudPlatform/k8s-stackdriver/issues/161)
* Fix failing to send metrics after container was just created/restarted (https://github.com/GoogleCloudPlatform/k8s-stackdriver/issues/160)
```

Bum version of kubelet-to-gcm to 1.2.6

---

custom-metrics-stackdriver-adapter/deploy/production/adapter.yaml
custom-metrics-stackdriver-adapter/deploy/staging/adapter_new_resource_model.yaml
custom-metrics-stackdriver-adapter/deploy/staging/adapter_old_resource_model.yaml

This caused Custom Metrics - Stackdriver Adapter e2e tests to fail.

[Custom Metrics] Remove priority field from apiservice definitions

---

prometheus-to-sd/config/common_config.go
prometheus-to-sd/config/source_config.go
prometheus-to-sd/config/source_config_test.go
prometheus-to-sd/main.go

Until now all the sources were on the same pod, but as we prepare for changing prometheus to a daemon set, now it makes sense to include the pod configuration in the source configuration
This is a small refactoring for the upcoming daemon set changes

[prometheus-to-sd] Add PodConfig in SourceConfig

---

hack/verify-flags/exceptions.txt
prometheus-to-sd/README.md
prometheus-to-sd/config/common_config.go
prometheus-to-sd/config/dynamic_source.go
prometheus-to-sd/config/dynamic_source_test.go
prometheus-to-sd/config/pod_config_test.go
prometheus-to-sd/config/source_config.go
prometheus-to-sd/config/source_config_test.go
prometheus-to-sd/main.go
prometheus-to-sd/translator/translator.go
prometheus-to-sd/translator/translator_test.go

Fixes #173.  See the issue for details.
```release-note
Adds the `container-name-label`, `pod-id-label`, `namespace-id-label` flags which allow prometheus labels to be used for SD resource labels.
```

[prometheus-to-sd] Allow using prometheus labels for SD resource

---

custom-metrics-stackdriver-adapter/Makefile
custom-metrics-stackdriver-adapter/pkg/adapter/provider/translator.go
custom-metrics-stackdriver-adapter/pkg/adapter/provider/translator_test.go
custom-metrics-stackdriver-adapter/pkg/adapter/server/start.go

Addresses https://github.com/GoogleCloudPlatform/k8s-stackdriver/issues/205
I tried to keep my changes as minimal as possible as I don't really have the bandwidth or expertise to do a large refactor. This has been tested in my environment to maintain existing functionality, as well as access to metrics in other projects. Adding scope was necessary to allow a service account to work, rather than GCE creds.
I would be happy to contribute documentation if this PR's code is deemed mergable.
Example spec:
```
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
name: dummy
namespace: default
spec:
scaleTargetRef:
apiVersion: apps/v1beta1
kind: Deployment
name: dummy
minReplicas: 1
maxReplicas: 5
metrics:
- external:
metricName: …
```

add support for other projects for external metrics

---

hack/verify-flags/known-flags.txt
prometheus-to-sd/config/common_config.go
prometheus-to-sd/main.go
prometheus-to-sd/translator/prometheus.go
prometheus-to-sd/translator/translator.go
prometheus-to-sd/translator/translator_test.go

This PR adds the ability to optionally downcase metric names (if it is so desired). It can be enabled via a command line flag and is defaulted to false. This is possibly desirable if stackdriver metric naming conventions are not in line with the actual metric names we want to import to stackdriver.

add ability to optionally downcase all metric names, in case metric names do not conform to stackdriver naming conventions

---

prometheus-to-sd/main.go
prometheus-to-sd/translator/prometheus.go
prometheus-to-sd/translator/translator.go
prometheus-to-sd/translator/translator_test.go

This PR adds partial summary metric importing ability for prom-to-sd (partially addressing #196). There are some important caveats, however:
1. Quantile metric data is disregarded, mostly because [it doesn't make a whole lot of sense to aggregate over the quantile metric data](https://prometheus.io/docs/practices/histograms/#errors-of-quantile-estimation). Aggregating across this data will give you averages. You will lose quantile information.
2. If you want to import summary metric information, you must first ensure that the metric you are summing does not have negative values ([this is despite the fact that prometheus documentation expressly allows for this possibility](https://prometheus.io/docs/practices/histograms/#count-and-sum-of-observations)). Unfortunately, this must be the case …

add partial summary support for metric imports

---

prometheus-to-sd/Makefile

There is only one undirect change in base image. See https://github.com/GoogleContainerTools/distroless/pull/296.
Without it image doesn't work in containerd env.

Bump version of prometheus-to-sd.

---

kubelet-to-gcm/monitor/kubelet/translate.go
kubelet-to-gcm/monitor/kubelet/translate_test.go

Fixes https://github.com/GoogleCloudPlatform/k8s-stackdriver/issues/233.
Summary stats for CRI integration can return nil fields for terminated containers, we should not skip the whole stats population for a single nil container stats.

Do not skip whole stats population for single nil stats.

---

kubelet-to-gcm/Makefile

New version to include fix from https://github.com/GoogleCloudPlatform/k8s-stackdriver/pull/236

Bump kubelet-to-gcm version to 1.2.9

---

hack/verify-flags/exceptions.txt
kubelet-to-gcm/monitor/kubelet/translate.go
kubelet-to-gcm/monitor/kubelet/translate_test.go

Support collecting stats for system containers. These stats are very useful, especially the `kubelet` one and `runtime` one.
An example:
```json
"systemContainers": [
{
"name": "kubelet",
"startTime": "2018-12-19T10:50:26Z",
"cpu": {
"time": "2019-03-08T08:53:41Z",
"usageNanoCores": 33617729,
"usageCoreNanoSeconds": 298544078034837
},
"memory": {
"time": "2019-03-08T08:53:41Z",
"usageBytes": 245764096,
"workingSetBytes": 245534720,
"rssBytes": 88256512,
"pageFaults": 3384427256,
"majorPageFaults": 2413
},
"userDefinedMetrics": null
},
{
"name": "runtime",
"startTime": "2018-12-19T10:50:26Z",
"cpu": {
"time": "2019-03-08T08:53:36Z",
"usageNanoCores": 429159480,
"usageCoreNanoSeconds": 1172508115040995
},
"memory": {
"time": "2019-03-08T08:53:36Z",
"usageBytes": 685658112, …
```

Collect system container stats.

---

kubelet-to-gcm/Makefile
kubelet-to-gcm/monitor/kubelet/translate_test.go

New in this version: pushing metrics for system containers.

Bump kubelet-to-gcm version to 1.2.10

---

kubelet-to-gcm/Dockerfile

This is part of the effort described in kep kubernetes/enhancements#900

Rebase kubelet-to-gcm to distroless

---

event-exporter/Makefile
kubelet-to-gcm/Makefile

Bump versions for new release, which builds images from distroless.

Bump Kubelet to GCM and Event Exporter versions

---

prometheus-to-sd/translator/translator.go
prometheus-to-sd/translator/translator_test.go

Fixes #261 . Interprets UNTYPED metrics as a GAUGE of type DOUBLE.

Add support for UNTYPED metrics

---

prometheus-to-sd/README.md
prometheus-to-sd/config/dynamic_source.go
prometheus-to-sd/config/dynamic_source_test.go
prometheus-to-sd/config/source_config.go
prometheus-to-sd/config/source_config_test.go
prometheus-to-sd/translator/translator.go
prometheus-to-sd/translator/translator_test.go

In order to allow for exporting by container name, or other label values, this PR adds the ability to filter by prometheus label values before exporting to stackdriver.

Add filtering by prometheus label to prom-to-sd

---

hack/verify-flags/exceptions.txt
hack/verify-flags/known-flags.txt
prometheus-to-sd/config/gce_config.go
prometheus-to-sd/main.go

To use application default credentials, a secret needs to be mounted with the json creds,
and exposed via GOOGLE_APPLICATION_CREDENTIALS environment variable.
Here are the relevant parts of the yaml I used.
spec:
containers:
- args:
- /monitor
- --source=gke-connect-agent:http://10.103.158.164:8080
- --stackdriver-prefix=custom.googleapis.com
- --manual-project=YOUR-PROJECT
- --zone-override=us-central1-a
- --manual-cluster=minikube-cluster
- --manual-instance=MyGkeConnectAgent
env:
- name: GOOGLE_APPLICATION_CREDENTIALS
value: /etc/creds/creds-gcp.json
volumeMounts:
- mountPath: /etc/creds
name: creds-gcp
readOnly: true
volumes:
- name: creds-gcp
secret:
defaultMode: 420
secretName: creds-gcp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …

Allow specifying metadata from flags, for use when not on GCE.

---

prometheus-to-sd/main.go
prometheus-to-sd/translator/metrics.go
prometheus-to-sd/translator/stackdriver.go
prometheus-to-sd/translator/translator.go
prometheus-to-sd/translator/translator_test.go

It will help to estimate delay between moment when metric was scraped
and when it was send to the Stackdriver.

Add latency metric to prometheus-to-sd.

---

prometheus-to-sd/Makefile

0.7.1 was already released. It wasn't reflected in the file.

Bump version of prometheus-to-sd to 0.7.2.

---

hack/verify-flags/exceptions.txt
prometheus-to-sd/Makefile
prometheus-to-sd/README.md
prometheus-to-sd/config/gce_config.go
prometheus-to-sd/main.go
prometheus-to-sd/translator/translator.go
prometheus-to-sd/translator/translator_test.go

Default project_id, cluster_name, location, and instance_id (or node_name) labels to values from GCE metadata server.

Add default value from GCE metadata server, when resource label flags

---

prometheus-to-sd/README.md

The motivation is that the Stackdriver support team gets user requests to support prometheus-to-sd, even though we have an alternative that some of these users aren't aware of.

Added comparison with stackdriver-prometheus

---

kubelet-to-gcm/monitor/main/daemon.go

schemaPrefix values:
"" - old resource model used, "gke_container"
"k8s_" - new resource model, with separate pod/container/node

Change default schemaPrefix flag in kubelet-to-gcm

---

event-exporter/main.go

Just close the stop channel to make sure every goroutine will receive stop signal. Otherwise event-exporter won't exit if received system terminating signal
#329

Close event-exporter's stop channel after system terminating signal.

---

hack/verify-flags/known-flags.txt
prometheus-to-sd/Makefile
prometheus-to-sd/main.go

prometheus-to-sd : stop exposing metrics on all interfaces by default, listen just on localhost

prometheus-to-sd : stop exposing /debug/expvars endpoint on all interfaces by default

---

README.md

Update README to note that tools in this repository are integrated
out of the box with GKE. These tools are not meant for end users.
Change Stackdriver to Cloud Operations.

Note out of the box integration with GKE

---

prometheus-to-sd/README.md

Google Cloud Monitoring develops and maintains stackdriver-prometheus to for GKE users. 
It is well supported and designed to meet expectations of Prometheus users. Many GKE
users are confused by the current README, use Prometheus integration from this repository
and run into issues. Highlighting this on top clears the confusion.

Highlight supported Prometheus integration on top

---

prometheus-to-sd/main.go

cc @amujumdar @x13n @44past4 
This PR proposes using `DefaultTokenSource` instead of `ComputeTokenSource` as the token source to fall back on when no explicit token URL or project override is specified. The implication of using [DefaultTokenSource](https://github.com/golang/oauth2/blob/cdc340f7c179dbbfa4afd43b7614e8fcadde4269/google/default.go#L43) is that it'll attempt to load credentials from the location specified via `GOOGLE_APPLICATION_CREDENTIALS` and a few others before falling back to `ComputeTokenSource` (if the application is running on GCE).
Fixes #66 .

Use default token source when no token URL or project override is provided

---

prometheus-to-sd/Makefile

cc @x13n 
Bump `prom-to-sd` version to pick up the changes in #349 to use `DefaultTokenSource` when no token URL or project override is provided.
If the change is deemed backward incompatible enough to justify a major version bump, happy to do so.

Bump prom-to-sd version to use DefaultTokenSource by default

---

custom-metrics-stackdriver-adapter/Dockerfile
custom-metrics-stackdriver-adapter/Makefile

Update the base image used for the custom-metrics-stackdriver-adapter to
fix CVE-2017-14062

Update custom-metrics-stackdriver-adapter base image

---

event-exporter/Makefile
event-exporter/sinks/stackdriver/sink.go

This label isn't very useful and can have very high cardinality.

Remove `component` label from received_entry_count metric

---

custom-metrics-stackdriver-adapter/Dockerfile

Rebasing the k8s images to distroless/static can make the images thinner, safer and less vulnerable.
Meanwhile, it will drastically reduce churn on the total number of k8s images versions. Due to the fact that many images are based on debian base and a vulnerability in debian base (a couple times a month) will result in rebuilding every image, changing the image from debian base to distroless/static can reduce the total number of k8s image versions.
See: https://github.com/kubernetes/enhancements/tree/master/keps/sig-release/1729-rebase-images-to-distroless
https://github.com/kubernetes/enhancements/issues/1729

Rebase custom-metrics-sd-adapter on `distroless`

---

event-exporter/Makefile
event-exporter/watchers/events/watcher.go
event-exporter/watchers/watcher.go

In large clusters, we see up to 1M events and fetching them using default 500 page size is impossible due to limited token expiration time.
/assign @serathius

Use 10000 page size on listing events.

---

custom-metrics-stackdriver-adapter/adapter.go
custom-metrics-stackdriver-adapter/pkg/adapter/coreprovider/client.go
custom-metrics-stackdriver-adapter/pkg/adapter/provider/provider.go
custom-metrics-stackdriver-adapter/pkg/adapter/translator/query_builder.go
custom-metrics-stackdriver-adapter/pkg/adapter/translator/query_builder_test.go
custom-metrics-stackdriver-adapter/pkg/adapter/translator/translator_test_utils.go
hack/verify-flags/exceptions.txt
hack/verify-flags/known-flags.txt

This PR adds the initial capability to support HPA based on Stackdriver distributions. It uses a special selector to signal that a distribution is intended: `reducer`. This is desired to enable scaling based on measures such as request latency percentiles.
This should allow usage of resources similar to:
```yaml
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
name: productcatalogservice
namespace: default
spec:
minReplicas: 1
maxReplicas: 5
metrics:
- external:
metricName: istio.io|service|server|response_latencies
metricSelector:
matchLabels:
metric.labels.destination_workload_name: productcatalogservice
reducer: PERCENTILE_99
targetAverageValue: "2"
type: External
scaleTargetRef:
apiVersion: apps/v1
kind: Deployment
name: productcatalogservice
```

Add flag-protected support for distributions

---

prometheus-to-sd/main.go

One invocation of google.DefaultTokenSource() is missing the scope
parameter. This results in that particular authentication flow failing
to fetch a token due to an empty set of scopes in the request. This PR
sets a wide scope matching another invocation of a similar method. IAM
should restrict perms further.
fixes: #401

Missing Scopes in call to DefaultTokenSource()

---

kubelet-to-gcm/Makefile
kubelet-to-gcm/monitor/main/daemon.go

This isn't really used and occassionally causes problems. Leaving the functionality for now to make rolling back easier.

Stop talking to kube-controller-manager from kubelet-to-gcm when port is set to 0

---

kubelet-to-gcm/Makefile
kubelet-to-gcm/monitor/kubelet/translate.go
kubelet-to-gcm/monitor/kubelet/translate_test.go

Right after container is started, kubelet returns time == start_time for
that metric, which causes Monitoring API to return 400 error.

Prevent invalid timestamps in page_fault_count metric

---

kubelet-to-gcm/Makefile
kubelet-to-gcm/monitor/kubelet/translate.go
kubelet-to-gcm/monitor/kubelet/translate_test.go

Turns out CPU metrics are also affected. Verified there are no other errors.

Prevent invalid timestamps in cpu usage metrics

---

custom-metrics-stackdriver-adapter/examples/direct-to-sd/Dockerfile
custom-metrics-stackdriver-adapter/examples/direct-to-sd/Makefile
custom-metrics-stackdriver-adapter/examples/direct-to-sd/custom-metrics-sd.yaml

Why?
This fixes some CVE issues [1] with
gcr.io/google-containers/sd-dummy-exporter:v0.2.0, which is based on
alpine:latest.
[1] CVE-2018-12020 CVE-2017-12837 CVE-2018-15688 CVE-2017-10140
CVE-2017-7526 CVE-2018-6913 CVE-2018-16864 CVE-2017-12883 CVE-2018-12015
CVE-2018-16865
I also pushed the new image to gcr.io/ to gcr.io/google-samples/

Rebase sd-dummy-exporter to distroless

---

custom-metrics-stackdriver-adapter/examples/prometheus-to-sd/Dockerfile
custom-metrics-stackdriver-adapter/examples/prometheus-to-sd/Makefile
custom-metrics-stackdriver-adapter/examples/prometheus-to-sd/README.md
custom-metrics-stackdriver-adapter/examples/prometheus-to-sd/custom-metrics-prometheus-sd.yaml
custom-metrics-stackdriver-adapter/examples/prometheus-to-sd/prometheus_dummy_exporter.go

This fixes some CVE issues [1] found in
gcr.io/google-containers/prometheus-dummy-exporter:v0.1.0, which is
based on alpine:latest
[1] CVE-2017-12883 CVE-2017-10140 CVE-2018-16865 CVE-2018-6913
CVE-2018-12015 CVE-2018-12020 CVE-2017-7526 CVE-2018-16864
CVE-2017-12837 CVE-2018-15688
Side changes: I updated some files to use newer APIs

Rebase prometheus-dummy-exporter on distroless

---

custom-metrics-stackdriver-adapter/deploy/staging/adapter_old_resource_model.yaml

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/autoscaling/custom_metrics_stackdriver_autoscaling.go:55
Jun  7 05:26:47.962: Failed to set up: error running /workspace/kubernetes/platforms/linux/amd64/kubectl --server=https://34.105.46.188 --kubeconfig=/workspace/.kube/config apply -f https://raw.githubusercontent.com/GoogleCloudPlatform/k8s-stackdriver/master/custom-metrics-stackdriver-adapter/deploy/staging/adapter_old_resource_model.yaml:
Command stdout:
namespace/custom-metrics created
serviceaccount/custom-metrics-stackdriver-adapter created
clusterrolebinding.rbac.authorization.k8s.io/custom-metrics:system:auth-delegator created
rolebinding.rbac.authorization.k8s.io/custom-metrics-auth-reader created …
```

apiVersion rbac.authorization.k8s.io/v1 for ClusterRoleBinding

---

event-exporter/sinks/stackdriver/log_entry_factory.go
event-exporter/sinks/stackdriver/monitored_resource_factory.go
event-exporter/sinks/stackdriver/monitored_resource_factory_config.go
event-exporter/sinks/stackdriver/monitored_resource_factory_test.go
event-exporter/sinks/stackdriver/sink.go
event-exporter/sinks/stackdriver/sink_config.go
event-exporter/sinks/stackdriver/sink_factory.go
event-exporter/sinks/stackdriver/writer.go
event-exporter/watchers/events/handler.go
event-exporter/watchers/events/watcher.go
event-exporter/watchers/watcher.go

Refactor monitored_resource_factory.go by removing redundant `config`
field and renaming existing `labels` field.
Also add comments in various files to improve readability.
Tested: make test

Refactor monitored_resource_factory.go

---

prometheus-to-sd/config/gce_config.go

When running in GKE with workload identity enabled, prometheus-to-sd
will enter a crashloop unless you run it with host-networking enabled
which will bypass the GKE metadata server. This solves that issue by
utilizing instance/hostname when instance/name isn't available.
Fixes: #399

Utilize hostname when instance/node unavailable.

---

event-exporter/sinks/stackdriver/sink.go
event-exporter/sinks/stackdriver/writer.go

Currently the metric is incremented regardless the request is
succeessfully sent to Cloud Logging. It should only be incremented when
the request succeeds.

Fix stackdriver_sink_successfully_sent_entry_count.

---

custom-metrics-stackdriver-adapter/deploy/production/adapter_new_resource_model.yaml
custom-metrics-stackdriver-adapter/deploy/staging/adapter_new_resource_model.yaml

The current metrics adapter deployment does not
currently set the fallback-for-container-metrics
flag.  In order to work with GKE workload metrics,
this needs to be set to true.
Signed-off-by: Gari Singh <gari.r.singh@gmail.com>

Enable fallback to k8s_container metrics

---

event-exporter/sinks/stackdriver/log_entry_factory.go
event-exporter/sinks/stackdriver/log_entry_factory_test.go

If lastTImestamp and lastObservedTimestamp are not set, Event Exporter
will not set log entry timestamp. In this case, Cloud Logging will set
the timestamp to the time when Cloud Logging receives the entry.

Update Event Exporter log entry timestamp.

---

event-exporter/Makefile
event-exporter/sinks/stackdriver/sink.go
event-exporter/watchers/events/watcher.go
event-exporter/watchers/storage.go

* event-exporter is a single replica deployment on user nodes. It currently consumes a significant amount of memory for large clusters (e.g., 800MB for 5k node cluster, 3.5 GB for 15k node cluster).
* To improve memory usage, we no longer store any watched events in memory and we only store a limited (1 item)  amount of listed events to assist with Watch. 
* After the improvement, memory is < 25 MB and does not increase with the number of nodes or events (e.g., 17 MB in 100 node cluster,  19 MB in 5k node cluster, 20 MB in 15k node cluster).
* The improvement does not change CPU usage and logging completeness.
See details in the design doc: https://docs.google.com/document/d/1i5v0N5YdT6nPXA4Uv7Ia6pDCzLONY_X85V7RWfpdHtM/edit?usp=sharing&resourcekey=0-oW6Lg-3i71XewhXI6kUtPA

Improve memory usage of event-exporter

---

event-exporter/sinks/stackdriver/metrics.go

Currently 99.9% latency reaches 113.388 which is the start
of the highest bucket
(https://screenshot.googleplex.com/DoW7T2fG3VZiJiq). Slightly increase bucket size and add more buckets so that we can distribute data points with higher values in different buckets.

Increase factor and count of record_latency_seconds.

---

custom-metrics-stackdriver-adapter/examples/direct-to-sd/custom-metrics-sd.yaml
custom-metrics-stackdriver-adapter/examples/prometheus-to-sd/custom-metrics-prometheus-sd.yaml

Provided that `autoscaling/v2beta2` will be deprecated since `Kubernetes v1.26`, and `autoscaling/v2` version has all the features needed in the example. We change the HPA api versions to `autoscaling/v2` in examples.
According to the Kubernetes [doc](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#scaling-on-custom-metrics), scaling on custom metrics feature after _Kubernetes v1.23 Stable_. Therefore, from my perspective, updating the HPA api version in the example to use `autoscaling/v2` should be sufficient.

[Enhance] Update autoscaling api version to v2 in prometheus example

---

custom-metrics-stackdriver-adapter/Dockerfile
custom-metrics-stackdriver-adapter/Makefile
custom-metrics-stackdriver-adapter/go.mod
custom-metrics-stackdriver-adapter/go.sum

Bump golang version to 1.19 to resolve some vulnerabilities, and update tag to patch version `v0.13.1`

Update stackdriver adapter tag

---

custom-metrics-stackdriver-adapter/examples/direct-to-sd/custom-metrics-sd.yaml

Fixing issue when
```sh
kubectl apply -f custom-metrics-sd.yaml
```
gives the following error:
>error: error validating "examples/direct-to-sd/custom-metrics-sd.yaml": error validating data: [ValidationError(HorizontalPodAutoscaler.spec.metrics[0].pods): unknown field "metricName" in io.k8s.api.autoscaling.v2.PodsMetricSource, ValidationError(HorizontalPodAutoscaler.spec.metrics[0].pods): unknown field "targetAverageValue" in io.k8s.api.autoscaling.v2.PodsMetricSource, ValidationError(HorizontalPodAutoscaler.spec.metrics[0].pods): missing required field "metric" in io.k8s.api.autoscaling.v2.PodsMetricSource, ValidationError(HorizontalPodAutoscaler.spec.metrics[0].pods): missing required field "target" in io.k8s.api.autoscaling.v2.PodsMetricSource]; if you choose to ignore these errors, …

Fix autoscaling v2 attribute

---

prometheus-to-sd/Dockerfile

govendor is no longer usable in our builds and has been replaced by go.mod for a while now.
Instead we'll rely on our internal license scanner for injecting notices and sources.

remove deprecated govendor license generation

---

prometheus-to-sd/Makefile

With the last PR we didn't bump that tag expecting it would still result in correct build tags.

fix build tag

---

.github/dependabot.yaml

Enable Dependabot for `Dockerfile` and `go.mod` dependency updates. 
This should hopefully help keep our go module and base / builder images up to date.
The PR was generated by a script, I used this as an opportunity to do a sanity check. Let me know if I should change any of the configuration values.

Install Dependabot to support Docker and go module updates

---

.github/dependabot.yaml

This should make ensure dependabot operates on each, and ignore the "archived" directory.

Update dependabot config to explicitly list directories

---

custom-metrics-stackdriver-adapter/Makefile
custom-metrics-stackdriver-adapter/adapter.go
custom-metrics-stackdriver-adapter/pkg/adapter/provider/provider.go

Adapted from https://github.com/GoogleCloudPlatform/k8s-stackdriver/pull/311
Also,
1. Instead of returning empty, this PR returns 1 metric resource item. Because returning empty response is not fine for generic clients that list resources with api discovery, like the namespace garbage collector and GitOps serivces like Config Sync and ArgoCD. An APIService that returns an empty list is invalid and causes an error in client-go.
1. added a feature-gate `list-full-custom-metrics` with default value = false.
1. metricsCache is the same as before previous.
Fixes: https://github.com/GoogleCloudPlatform/k8s-stackdriver/issues/582, https://github.com/GoogleCloudPlatform/k8s-stackdriver/issues/545, https://github.com/GoogleCloudPlatform/k8s-stackdriver/issues/510, …

Fix OOM and "http2: stream closed" issue by only returning one item in ListAllMetrics by default

---

custom-metrics-stackdriver-adapter/deploy/production/adapter.yaml
custom-metrics-stackdriver-adapter/deploy/production/adapter_new_resource_model.yaml
custom-metrics-stackdriver-adapter/deploy/staging/adapter_new_resource_model.yaml
custom-metrics-stackdriver-adapter/deploy/staging/adapter_old_resource_model.yaml
custom-metrics-stackdriver-adapter/deploy/test/adapter_new_resource_model_with_core_metrics.yaml

At least 2 people have tested this image.
Also revert memory limit to 200Mi (increasing to 400Mi was a short-term mitigation)
Fixes: #545

Update custom-metrics-stackdriver-adapter version to v0.14.2-gke.0

---

custom-metrics-stackdriver-adapter/adapter-beta.yaml
custom-metrics-stackdriver-adapter/deploy/production/adapter.yaml
custom-metrics-stackdriver-adapter/deploy/production/adapter_new_resource_model.yaml
custom-metrics-stackdriver-adapter/deploy/staging/adapter_new_resource_model.yaml
custom-metrics-stackdriver-adapter/deploy/staging/adapter_old_resource_model.yaml
custom-metrics-stackdriver-adapter/deploy/test/adapter_new_resource_model_with_core_metrics.yaml
custom-metrics-stackdriver-adapter/pkg/adapter/coreprovider/coreprovider_test.go

Fixes: [#485](https://github.com/GoogleCloudPlatform/k8s-stackdriver/issues/485)
Tested: 
```
curl -k https://localhost:6443/livez
ok
curl -k https://localhost:6443/readyz
ok
k top pods -n custom-metrics
NAME                                                 CPU(cores)   MEMORY(bytes)   
custom-metrics-stackdriver-adapter-cddcdcf54-vdhlj   3m           32Mi 
```

Add readiness and liveness probe

---

custom-metrics-stackdriver-adapter/adapter-beta.yaml
custom-metrics-stackdriver-adapter/deploy/production/adapter.yaml
custom-metrics-stackdriver-adapter/deploy/production/adapter_new_resource_model.yaml
custom-metrics-stackdriver-adapter/deploy/staging/adapter_new_resource_model.yaml
custom-metrics-stackdriver-adapter/deploy/staging/adapter_old_resource_model.yaml
custom-metrics-stackdriver-adapter/deploy/test/adapter_new_resource_model_with_core_metrics.yaml
custom-metrics-stackdriver-adapter/pkg/adapter/coreprovider/coreprovider_test.go

Reverts GoogleCloudPlatform/k8s-stackdriver#710
Fixes https://github.com/GoogleCloudPlatform/k8s-stackdriver/issues/721
Changing port number might bring downtime.

Revert "Add readiness and liveness probe"

---

custom-metrics-stackdriver-adapter/deploy/production/adapter.yaml
custom-metrics-stackdriver-adapter/deploy/production/adapter_new_resource_model.yaml
custom-metrics-stackdriver-adapter/deploy/staging/adapter_new_resource_model.yaml
custom-metrics-stackdriver-adapter/deploy/staging/adapter_old_resource_model.yaml
custom-metrics-stackdriver-adapter/deploy/test/adapter_new_resource_model_with_core_metrics.yaml

Reverts GoogleCloudPlatform/k8s-stackdriver#712
client-go version was bumped in https://github.com/GoogleCloudPlatform/k8s-stackdriver/pull/690 to fix vulnerabilities. However, it seems causing https://github.com/GoogleCloudPlatform/k8s-stackdriver/issues/729.

Revert "Upgrade metrics adapter to v0.15.0-gke.0"

---

custom-metrics-stackdriver-adapter/deploy/production/adapter.yaml
custom-metrics-stackdriver-adapter/deploy/production/adapter_new_resource_model.yaml
custom-metrics-stackdriver-adapter/deploy/staging/adapter_new_resource_model.yaml
custom-metrics-stackdriver-adapter/deploy/staging/adapter_old_resource_model.yaml
custom-metrics-stackdriver-adapter/deploy/test/adapter_new_resource_model_with_core_metrics.yaml

Reverts GoogleCloudPlatform/k8s-stackdriver#735
#729
Now, we are 100% sure it's not related to our version bump around client-go. Because one user confirmed that same issue happened with this older version.

Revert "Revert "Upgrade metrics adapter to v0.15.0-gke.0""

---

prometheus-to-sd/translator/prometheus.go
prometheus-to-sd/translator/translator.go
prometheus-to-sd/translator/translator_test.go

Also add support for multiple response formats (text/proto)

prom-to-sd: Prefer proto in content type

---

prometheus-to-sd/main.go

prom-to-sd: Fix not respecting --api-override

---

prometheus-to-sd/Makefile

This is to fix the image tag for prometheus-to-sd. https://github.com/GoogleCloudPlatform/k8s-stackdriver/pull/845 didn't bump the tag to v0.12.2. This causes mismatch between image tag and repo tag.

Update image tag to v0.12.3 for prometheus-to-sd.

---

event-exporter/Makefile

To release the pod owner label feature.
Change-Id: I877d7be0cfb6358bd769d80ca12c57efd05bc18e

event-exporter: bump version to 0.5.0

---

custom-metrics-stackdriver-adapter/deploy/staging/adapter_new_resource_model_external_cache.yaml

This manifest is an exact copy of `adapter_new_resource_model.yaml` except that we enable the external cache via the `--external-metric-cache-ttl=1m` and we've updated to an image that is compatible with the feature.

Add manifest for deploying cm-sd-adapter with new external cache

---

kubelet-to-gcm/monitor/kubelet/translate.go
kubelet-to-gcm/monitor/kubelet/translate_test.go

Sometimes kubelet response on its /stats/summary endpoint can have missing data for `usageBytes` `pageFaults`, and `majorPageFaults` for container memory.
This change would skip those fields when unavailable, in stead of failing all metrics on that container.

skip certain memory metrics when not available

---

custom-metrics-stackdriver-adapter/deploy/production/adapter_new_resource_model.yaml
custom-metrics-stackdriver-adapter/deploy/staging/adapter_new_resource_model.yaml
custom-metrics-stackdriver-adapter/deploy/staging/adapter_new_resource_model_external_cache.yaml
custom-metrics-stackdriver-adapter/deploy/test/adapter_new_resource_model_with_core_metrics.yaml

Removes the `namespace` field from ClusterRole definitions in the adapter's deployment YAML files. ClusterRoles are cluster-scoped resources and should not have a namespace.
Fixes #492

Fix: Remove namespace from ClusterRole in adapter deployments

---

event-exporter/event_exporter.go
event-exporter/kubernetes/watchers/events/watcher.go
event-exporter/main.go

Remove [Options.Limit=1](https://github.com/GoogleCloudPlatform/k8s-stackdriver/blob/master/event-exporter/kubernetes/watchers/events/watcher.go#L76) when flag `enableRemoveOptionsLimit` flag is enabled. Default value is false.

Remove `Options.Limit=1` with a flag guarded for this change 

---

custom-metrics-stackdriver-adapter/Makefile
custom-metrics-stackdriver-adapter/go.mod
custom-metrics-stackdriver-adapter/go.sum
custom-metrics-stackdriver-adapter/pkg/api/openapi-gen.go

Add an explicit dependency on `k8s.io/kube-openapi/cmd/openapi-gen` to make go install run. Also change the target to use `go run` instead of `go install` so that we don't depend on GOPATH being set.
While I'm here also format the flags to make them more readable.

Fix `make update-generated` target.

---

README.md

This has caused some confusion among users (see https://github.com/GoogleCloudPlatform/k8s-stackdriver/issues/480#issuecomment-2493956681).
Fixes https://github.com/GoogleCloudPlatform/k8s-stackdriver/issues/480.

docs: clarify that stackdriver adapter is for end-users
